#!/bin/bash

concept=$( basename $2 | cut -d"_" -f2 | cut -d"." -f1 )

label=$( head -n1 $2 | cut -d" " -f2 )

l=2
if [ "$label" -ne "1" ]; then
	l=3
fi

# ajouter la troncature du fichier .out (1ere ligne en trop)

exec 6< $1
while read -r line
do
	read -r f2line <&6

	img=$( basename $f2line | cut -d"." -f1 ) 
	score=$( echo $line | cut -d" " -f$l )

	echo "$concept Q0 $img 0 $score R"

done <$2


