#!/bin/bash

for line in $(ls data/train/ann); do

name=$( echo $line | cut -d"." -f1 )

./script_fusion_histo_ann data/train/histo_sift_svm/sift.svm data/train/ann/$name.ann > data/train/svm_sift/color_$name.svm

./libsvm/svm-train -w+1 19 -b 1 -g 1.0 -h 0 data/train/svm_sift/color_$name.svm
mv color_$name.svm.model data/train/model_sift/color_$name.model

done
